/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cn_kotlin_ndkbuild_JNI */

#ifndef _Included_com_cn_kotlin_ndkbuild_JNI
#define _Included_com_cn_kotlin_ndkbuild_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cn_kotlin_ndkbuild_JNI
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cn_kotlin_ndkbuild_JNI_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_cn_kotlin_ndkbuild_JNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cn_kotlin_ndkbuild_JNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cn_kotlin_ndkbuild_JNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cn_kotlin_ndkbuild_JNI_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cn_kotlin_ndkbuild_JNI
 * Method:    increaseArrayElse
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_cn_kotlin_ndkbuild_JNI_increaseArrayElse
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_cn_kotlin_ndkbuild_JNI
 * Method:    checkPw
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cn_kotlin_ndkbuild_JNI_checkPw
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
